import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, authorization, apikey, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS"};
const BUCKET="character-photos",BYTES_MAX=1024*1024,TIPOS=new Set(["image/jpeg","image/png"]);
function resposta(obj:unknown,status=200){return new Response(JSON.stringify(obj),{status,headers:{...cors,"content-type":"application/json; charset=utf-8"}})}
function ok(dados:unknown){return resposta({ok:true,dados})}
function falha(codigo:string,mensagem:string,extra:unknown=null,status=400){return resposta({ok:false,erro:{codigo,mensagem,extra}},status)}
async function sha256Hex(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function personagemPublico(r:any){return{id:r.id,donoId:r.donoId,donoNome:r.donoNome,nome:r.nome,classe:r.classe,subclasse:r.subclasse,ancestralidade:r.ancestralidade,comunidade:r.comunidade,nivel:Number(r.nivel)||1,versao:Number(r.versao)||1,schema:Number(r.schema)||1,criadoEm:r.criadoEm,atualizadoEm:r.atualizadoEm,ficha:r.dados||{}}}
async function autenticar(db:any,token:string){if(!token)return null;const{data:s,error:e1}=await db.from("sessoes").select("row_id,jogadorId,expiraEm").eq("tokenHash",await sha256Hex(token)).maybeSingle();if(e1)throw e1;if(!s||!s.expiraEm||new Date(s.expiraEm).getTime()<Date.now())return null;const{data:j,error:e2}=await db.from("jogadores").select("id,nome,papel,ativo").eq("id",s.jogadorId).maybeSingle();if(e2)throw e2;if(!j||j.ativo===false)return null;await db.from("sessoes").update({ultimoUsoEm:new Date().toISOString()}).eq("row_id",s.row_id);return j}
async function personagem(db:any,j:any,id:string){const{data:r,error}=await db.from("personagens").select("*").eq("id",id).eq("excluido",false).maybeSingle();if(error)throw error;if(!r)return{erro:falha("NAO_ENCONTRADO","Personagem não encontrado.",null,404)};if(j.papel!=="mestre"&&String(r.donoId)!==String(j.id))return{erro:falha("SEM_PERMISSAO","Essa ficha não é sua.",null,403)};return{r}}
function storagePath(v:any){const s=String(v||"");return s.startsWith("characters/")&&/^[A-Za-z0-9_.\/-]+$/.test(s)?s:""}
async function atualizarFoto(db:any,j:any,r:any,nova:string){const ficha=r.dados&&typeof r.dados==="object"?JSON.parse(JSON.stringify(r.dados)):{};ficha.identidade=ficha.identidade&&typeof ficha.identidade==="object"?ficha.identidade:{};const antiga=String(ficha.identidade.foto||"");ficha.identidade.foto=nova;ficha.meta=ficha.meta&&typeof ficha.meta==="object"?ficha.meta:{};ficha.meta.schema=Number(r.schema)||1;const versaoAtual=Number(r.versao)||1,atualizadoEm=new Date().toISOString();const{data,error}=await db.from("personagens").update({dados:ficha,versao:versaoAtual+1,atualizadoEm}).eq("row_id",r.row_id).eq("versao",versaoAtual).select("*");if(error)throw error;if(!data||data.length!==1)return{conflito:true,antiga};try{await db.from("log").insert({quandoEm:atualizadoEm,jogadorId:j.id,jogadorNome:j.nome,acao:nova?"foto-trocada":"foto-removida",detalhe:r.nome})}catch{}return{personagem:personagemPublico(data[0]),antiga}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return falha("DADOS_INVALIDOS","Método não suportado.",null,405);try{const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}}),p=await req.json(),j=await autenticar(db,String(p?.token||""));if(!j)return falha("NAO_AUTENTICADO","Faça login para continuar.",null,401);const id=String(p?.id||"");if(!id)return falha("DADOS_INVALIDOS","ID do personagem ausente.");const pr=await personagem(db,j,id);if(pr.erro)return pr.erro;const r=pr.r;
if(p.acao==="guardarFoto"){const mime=String(p?.tipo||"").toLowerCase();if(!TIPOS.has(mime))return falha("DADOS_INVALIDOS","A foto precisa ser JPEG ou PNG.");const b64=String(p?.imagem||"").replace(/^data:[^,]+,/,"").trim();if(!b64)return falha("DADOS_INVALIDOS","Nenhuma imagem veio no pedido.");if(Math.floor(b64.length*3/4)>BYTES_MAX)return falha("DADOS_INVALIDOS","A foto passou de 1024 KB. Recorte de novo.");let bytes:Uint8Array;try{const bin=atob(b64);bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i)}catch{return falha("DADOS_INVALIDOS","A imagem chegou corrompida.")};if(bytes.byteLength>BYTES_MAX)return falha("DADOS_INVALIDOS","A foto passou de 1024 KB. Recorte de novo.");const ext=mime==="image/png"?"png":"jpg",path=`characters/${id}/${crypto.randomUUID()}.${ext}`;const{error:upErr}=await db.storage.from(BUCKET).upload(path,bytes,{contentType:mime,upsert:false,cacheControl:"3600"});if(upErr)throw upErr;const u=await atualizarFoto(db,j,r,path);if(u.conflito){await db.storage.from(BUCKET).remove([path]);return falha("CONFLITO","Essa ficha foi alterada em outro lugar. Recarregue antes de trocar a foto.",null,409)}const antiga=storagePath(u.antiga);if(antiga&&antiga!==path)await db.storage.from(BUCKET).remove([antiga]);return ok({personagem:u.personagem,foto:path})}
if(p.acao==="removerFoto"){const u=await atualizarFoto(db,j,r,"");if(u.conflito)return falha("CONFLITO","Essa ficha foi alterada em outro lugar. Recarregue antes de remover a foto.",null,409);const antiga=storagePath(u.antiga);if(antiga)await db.storage.from(BUCKET).remove([antiga]);return ok({personagem:u.personagem,foto:""})}
return falha("ACAO_DESCONHECIDA","Ação de foto desconhecida.",null,404)}catch(e){console.error(e);return falha("INTERNO",String((e as Error)?.message||"Erro inesperado ao tratar foto."),null,500)}});
