import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import bcrypt from "npm:bcryptjs@2.4.3";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, authorization, apikey, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS"};
const MAX_TENTATIVAS=5,BLOQUEIO_MS=15*60*1000,SESSAO_DIAS=60;
function resposta(obj:unknown,status=200){return new Response(JSON.stringify(obj),{status,headers:{...cors,"content-type":"application/json; charset=utf-8"}})}
function ok(dados:unknown){return resposta({ok:true,dados})}
function falha(codigo:string,mensagem:string,extra:unknown=null,status=400){return resposta({ok:false,erro:{codigo,mensagem,extra}},status)}
function normalizarNome(nome:unknown){return String(nome||"").trim().replace(/\s+/g," ").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function validarNome(nome:unknown){const v=String(nome||"").trim().replace(/\s+/g," ");if(v.length<2||v.length>24)return{ok:false,erro:"O nome precisa ter entre 2 e 24 caracteres."};if(!/^[\p{L}\p{N} ._'-]+$/u.test(v))return{ok:false,erro:"O nome tem caracteres não permitidos."};return{ok:true,valor:v}}
function validarCodigo(codigo:unknown){const v=String(codigo||"").trim();if(v.length<4||v.length>32)return{ok:false,erro:"O código precisa ter entre 4 e 32 caracteres."};return{ok:true,valor:v}}
function jogadorPublico(j:any){return{id:j.id,nome:j.nome,papel:j.papel,ehMestre:j.papel==="mestre"}}
function hexAleatorio(bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return Array.from(a).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function sha256Hex(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function registrarLog(db:any,j:any,acao:string,detalhe=""){try{await db.from("log").insert({quandoEm:new Date().toISOString(),jogadorId:j?.id||"",jogadorNome:j?.nome||"",acao,detalhe:String(detalhe).slice(0,500)})}catch{}}
async function criarSessao(db:any,id:string){const token=hexAleatorio(32),agora=new Date(),expira=new Date(agora.getTime()+SESSAO_DIAS*86400000);const{error}=await db.from("sessoes").insert({tokenHash:await sha256Hex(token),jogadorId:id,criadoEm:agora.toISOString(),expiraEm:expira.toISOString(),ultimoUsoEm:agora.toISOString()});if(error)throw error;return token}
async function exigirJogador(db:any,token:string){if(!token)return null;const{data:s,error:e1}=await db.from("sessoes").select("row_id,jogadorId,expiraEm").eq("tokenHash",await sha256Hex(token)).maybeSingle();if(e1)throw e1;if(!s||!s.expiraEm||new Date(s.expiraEm).getTime()<Date.now())return null;const{data:j,error:e2}=await db.from("jogadores").select("*").eq("id",s.jogadorId).maybeSingle();if(e2)throw e2;if(!j||j.ativo===false)return null;await db.from("sessoes").update({ultimoUsoEm:new Date().toISOString()}).eq("row_id",s.row_id);return j}
async function limite(db:any,chave:string){const{data,error}=await db.from("auth_rate_limits").select("*").eq("chave",chave).maybeSingle();if(error)throw error;if(!data)return{bloqueado:false,tentativas:0};const ate=data.bloqueado_ate?new Date(data.bloqueado_ate).getTime():0;if(ate&&ate>Date.now())return{bloqueado:true,tentativas:Number(data.tentativas)||0};if(ate&&ate<=Date.now()){await db.from("auth_rate_limits").delete().eq("chave",chave);return{bloqueado:false,tentativas:0}}return{bloqueado:false,tentativas:Number(data.tentativas)||0}}
async function falhou(db:any,chave:string){const atual=await limite(db,chave),n=atual.tentativas+1,bloqueadoAte=n>=MAX_TENTATIVAS?new Date(Date.now()+BLOQUEIO_MS).toISOString():null;await db.from("auth_rate_limits").upsert({chave,tentativas:n,bloqueado_ate:bloqueadoAte,atualizado_em:new Date().toISOString()},{onConflict:"chave"})}
async function limparFalhas(db:any,chave:string){await db.from("auth_rate_limits").delete().eq("chave",chave)}
async function loginBcrypt(db:any,j:any,codigo:string,chave:string){const hash=String(j.codigoHash||"");if(!hash.startsWith("$2"))return{legacy:true};if(!bcrypt.compareSync(codigo,hash)){await falhou(db,chave);return{erro:falha("CREDENCIAL_INVALIDA","Nome ou código incorreto.",null,401)}}await limparFalhas(db,chave);await db.from("jogadores").update({ultimoAcessoEm:new Date().toISOString()}).eq("id",j.id);const token=await criarSessao(db,j.id);await registrarLog(db,j,"login","supabase");return{token,jogador:j}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return falha("DADOS_INVALIDOS","Método não suportado.",null,405);try{const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}}),p=await req.json(),acao=String(p?.acao||"");
if(acao==="registrar"){const vn=validarNome(p?.nome);if(!vn.ok)return falha("DADOS_INVALIDOS",vn.erro!);const vc=validarCodigo(p?.codigo);if(!vc.ok)return falha("DADOS_INVALIDOS",vc.erro!);const chaveNome=normalizarNome(vn.valor);const{data:existente,error:e1}=await db.from("jogadores").select("id").eq("chaveNome",chaveNome).maybeSingle();if(e1)throw e1;if(existente)return falha("NOME_EM_USO","Já existe um jogador com esse nome.");const agora=new Date().toISOString(),j={id:crypto.randomUUID(),nome:vn.valor,chaveNome,papel:"jogador",codigoHash:bcrypt.hashSync(vc.valor,12),salt:"bcrypt",ativo:true,criadoEm:agora,ultimoAcessoEm:agora};const{error:e2}=await db.from("jogadores").insert(j);if(e2)throw e2;const token=await criarSessao(db,j.id);await registrarLog(db,j,"registro","novo jogador (supabase)");return ok({token,jogador:jogadorPublico(j)})}
if(acao==="entrar"){const chave=normalizarNome(p?.nome),rl=`j:${chave}`,l=await limite(db,rl);if(l.bloqueado)return falha("BLOQUEADO","Muitas tentativas. Tente de novo em 15 minutos.",null,429);const{data:j,error}=await db.from("jogadores").select("*").eq("chaveNome",chave).maybeSingle();if(error)throw error;if(!j||j.ativo===false){await falhou(db,rl);return falha("CREDENCIAL_INVALIDA","Nome ou código incorreto.",null,401)}const r=await loginBcrypt(db,j,String(p?.codigo||"").trim(),rl);if(r.legacy)return falha("LEGACY_AUTH","Conta ainda usa a autenticação antiga.",null,409);if(r.erro)return r.erro;return ok({token:r.token,jogador:jogadorPublico(r.jogador)})}
if(acao==="entrarMestre"){const l=await limite(db,"mestre");if(l.bloqueado)return falha("BLOQUEADO","Muitas tentativas. Tente de novo em 15 minutos.",null,429);const{data:j,error}=await db.from("jogadores").select("*").eq("id","mestre").maybeSingle();if(error)throw error;if(!j||j.ativo===false)return falha("MESTRE_NAO_CONFIGURADO","Mestre não configurado.",null,409);if(!String(j.codigoHash||"").startsWith("$2"))return falha("LEGACY_AUTH","Credencial do Mestre ainda usa a autenticação antiga.",null,409);const r=await loginBcrypt(db,j,String(p?.codigo||"").trim(),"mestre");if(r.erro)return r.erro;return ok({token:r.token,jogador:jogadorPublico(r.jogador)})}
if(acao==="migrarCredencial"){const j=await exigirJogador(db,String(p?.token||""));if(!j)return falha("NAO_AUTENTICADO","Sessão legada inválida ou expirada.",null,401);const vc=validarCodigo(p?.codigo);if(!vc.ok)return falha("DADOS_INVALIDOS",vc.erro!);if(String(j.codigoHash||"").startsWith("$2"))return ok({migrado:false,jaMigrado:true,jogador:jogadorPublico(j)});const{error}=await db.from("jogadores").update({codigoHash:bcrypt.hashSync(vc.valor,12),salt:"bcrypt",ultimoAcessoEm:new Date().toISOString()}).eq("id",j.id);if(error)throw error;await registrarLog(db,j,"credencial-migrada","bcrypt");return ok({migrado:true,jogador:jogadorPublico(j)})}
if(acao==="trocarCodigo"){const j=await exigirJogador(db,String(p?.token||""));if(!j)return falha("NAO_AUTENTICADO","Faça login para continuar.",null,401);const hash=String(j.codigoHash||"");if(!hash.startsWith("$2"))return falha("LEGACY_AUTH","Conta ainda usa a autenticação antiga.",null,409);if(!bcrypt.compareSync(String(p?.codigoAtual||"").trim(),hash))return falha("CREDENCIAL_INVALIDA","O código atual está incorreto.",null,401);const novo=validarCodigo(p?.codigoNovo);if(!novo.ok)return falha("DADOS_INVALIDOS",novo.erro!);const{error}=await db.from("jogadores").update({codigoHash:bcrypt.hashSync(novo.valor,12),salt:"bcrypt"}).eq("id",j.id);if(error)throw error;await registrarLog(db,j,"troca-codigo","supabase");return ok({trocado:true})}
return falha("ACAO_DESCONHECIDA","Ação de autenticação desconhecida.",null,404)}catch(e){console.error(e);return falha("INTERNO","Erro inesperado no servidor.",null,500)}});
